sudo: required
dist: trusty

language: haxe

haxe:
  - "3.2.1"
  - development
  
# matrix:
#   allow_failures:
#     - haxe: development
    
install:
  - haxelib install travix
  - haxelib run travix install

script:
  - haxelib run travix interp
  - haxelib run travix neko
  - haxelib run travix python
  - haxelib run travix node
  # - haxelib run travix flash
  - haxelib run travix java
  - haxelib run travix cpp
  - haxelib run travix cs
  - haxelib run travix php

env:
  secure: dhVtIkMcUYAyAK92oEzBiuHE2uH9MQ46PD8zdKnnky9WiH54x/Y167Wt1NvUhFxhNzfu44VpI5d1ngnSV5pwum+E/RfoJNoqIsRsy1dL/vnTwyBdGDwbBJc/RDqXYUQnF8okR3JBZKmr9FLXTl5DMKOP+mJE1IF6GLijTDR4pf8=

jobs:
  include:
    - stage: deploy
      os: linux
      haxe: "3.2.1"
      # matrix: null
      script: skip
      after_success: haxelib run travix release
